import { randomUUID } from "crypto";
import type {
  BorrowTransaction,
  CoinTransaction,
  Item,
  Notification,
  Place,
  Rating,
  RequestEntity,
  Trip,
  User,
} from "../types/domain";

const now = () => new Date().toISOString();
const future = (minutes: number) =>
  new Date(Date.now() + minutes * 60 * 1000).toISOString();

export const db = {
  users: [
    {
      id: "user-1",
      name: "Aarav Singh",
      email: "aarav@iitd.ac.in",
      hostelName: "Satpura",
      wing: "A",
      role: "STUDENT",
      coins: 220,
      karmaPoints: 34,
      rating: 4.8,
      successfulDeliveries: 12,
      successfulReturns: 5,
      cancellations: 1,
      reputationScore: 92,
      passwordHash: "$2b$10$abcdefghijklmnopqrstuv",
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "user-2",
      name: "Mira Kapoor",
      email: "mira@iitd.ac.in",
      hostelName: "Kumaon",
      wing: "C",
      role: "STUDENT",
      coins: 180,
      karmaPoints: 28,
      rating: 4.9,
      successfulDeliveries: 9,
      successfulReturns: 7,
      cancellations: 0,
      reputationScore: 95,
      passwordHash: "$2b$10$abcdefghijklmnopqrstuv",
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "admin-1",
      name: "Operations Admin",
      email: "ops@iitd.ac.in",
      hostelName: "Campus Housing",
      wing: "HQ",
      role: "ADMIN",
      coins: 1000,
      karmaPoints: 120,
      rating: 5,
      successfulDeliveries: 0,
      successfulReturns: 0,
      cancellations: 0,
      reputationScore: 100,
      passwordHash: "$2b$10$abcdefghijklmnopqrstuv",
      createdAt: now(),
      updatedAt: now(),
    },
  ] as User[],
  places: [
    {
      id: "place-night-mess",
      name: "Night Mess",
      type: "FOOD",
      latitude: 28.5458,
      longitude: 77.1922,
      radiusMeters: 120,
      createdAt: now(),
    },
    {
      id: "place-nescafe",
      name: "Nescafe",
      type: "CAFE",
      latitude: 28.5441,
      longitude: 77.1913,
      radiusMeters: 100,
      createdAt: now(),
    },
    {
      id: "place-sda",
      name: "SDA Market",
      type: "MARKET",
      latitude: 28.5471,
      longitude: 77.1975,
      radiusMeters: 200,
      createdAt: now(),
    },
  ] as Place[],
  requests: [
    {
      id: "request-1",
      title: "Need cold coffee and chips",
      description: "Pick up from Nescafe on your way to Satpura.",
      itemName: "Cold coffee combo",
      type: "CONSUMABLE",
      requesterId: "user-2",
      helperId: null,
      placeId: "place-nescafe",
      tripId: null,
      status: "OPEN",
      rewardCoins: 24,
      depositCoins: 24,
      isUrgent: false,
      expiresAt: future(90),
      createdAt: now(),
      updatedAt: now(),
    },
  ] as RequestEntity[],
  trips: [
    {
      id: "trip-1",
      title: "Satpura to Night Mess",
      helperId: "user-1",
      startPlaceId: "place-night-mess",
      destinationLabel: "Satpura Hostel",
      departureTime: future(20),
      availableSlots: 3,
      occupiedSlots: 1,
      status: "MATCHING",
      geofenceTag: "hostel-food-route",
      notes: "Can carry drinks and medicines.",
      createdAt: now(),
      updatedAt: now(),
    },
  ] as Trip[],
  items: [
    {
      id: "item-1",
      ownerId: "user-1",
      title: "Casio scientific calculator",
      description: "Good for exam week emergency borrowing.",
      category: "ACADEMICS",
      securityDepositCoins: 60,
      dailyRateCoins: 10,
      status: "AVAILABLE",
      createdAt: now(),
      updatedAt: now(),
    },
  ] as Item[],
  borrowTransactions: [] as BorrowTransaction[],
  notifications: [
    {
      id: "notification-1",
      userId: "user-1",
      title: "Urgent request near Nescafe",
      body: "A medicine request is available within your walking route.",
      type: "URGENT_REQUEST",
      priority: "URGENT",
      read: false,
      cooldownKey: "place-nescafe-user-1",
      createdAt: now(),
    },
  ] as Notification[],
  coinTransactions: [
    {
      id: "coin-1",
      userId: "user-1",
      amount: 20,
      type: "EARN",
      direction: "CREDIT",
      reference: "seed",
      description: "Welcome bonus",
      createdAt: now(),
    },
  ] as CoinTransaction[],
  ratings: [] as Rating[],
};

export function makeId(prefix: string) {
  return `${prefix}-${randomUUID()}`;
}
